// <auto-generated />
using MandrilAPI.Models.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MandrilAPI.Migrations
{
    [DbContext(typeof(MandrilDbContext))]
    [Migration("20250613134846_Init3")]
    partial class Init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MandrilAPI.Models.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Potencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("MandrilAPI.Models.Mandril", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Mandrils");
                });

            modelBuilder.Entity("MandrilAPI.Models.MandrilHabilidades", b =>
                {
                    b.Property<int>("Mandrilid")
                        .HasColumnType("int");

                    b.Property<int>("Habilidadid")
                        .HasColumnType("int");

                    b.Property<int>("PotenciaMH")
                        .HasColumnType("int");

                    b.HasKey("Mandrilid", "Habilidadid");

                    b.HasIndex("Habilidadid");

                    b.ToTable("MandrilHabilidades", t =>
                        {
                            t.HasCheckConstraint("CK_MandrilHabilidad_Potencia_Max4", "[PotenciaMH] <= 4");
                        });
                });

            modelBuilder.Entity("MandrilAPI.Models.MandrilHabilidades", b =>
                {
                    b.HasOne("MandrilAPI.Models.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("Habilidadid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MandrilAPI.Models.Mandril", "Mandril")
                        .WithMany()
                        .HasForeignKey("Mandrilid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Mandril");
                });
#pragma warning restore 612, 618
        }
    }
}
