// <auto-generated />

using MandrilAPI.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MandrilAPI.Infrastructure.Migrations
{
    [DbContext(typeof(MandrilDbContext))]
    [Migration("20250717143436_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MandrilAPI.DatabaseContext.MandrilWithSkillsIntermediateTable", b =>
                {
                    b.Property<int>("MandrilId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("PowerMS")
                        .HasColumnType("int");

                    b.HasKey("MandrilId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("MandrilWithSkills", null, t =>
                        {
                            t.HasCheckConstraint("power_limit_4", "PowerMS <= 4");
                        });
                });

            modelBuilder.Entity("MandrilAPI.Models.Mandril", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Mandrils");
                });

            modelBuilder.Entity("MandrilAPI.Models.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("MandrilAPI.DatabaseContext.MandrilWithSkillsIntermediateTable", b =>
                {
                    b.HasOne("MandrilAPI.Models.Mandril", "Mandril")
                        .WithMany()
                        .HasForeignKey("MandrilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MandrilAPI.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandril");

                    b.Navigation("Skill");
                });
#pragma warning restore 612, 618
        }
    }
}
