// <auto-generated />
using MandrilAPI.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MandrilAPI.Migrations
{
    [DbContext(typeof(MandrilDbContext))]
    partial class MandrilDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MandrilAPI.Domain.Models.Mandril", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Mandrils");
                });

            modelBuilder.Entity("MandrilAPI.Domain.Models.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("MandrilAPI.Infrastructure.DatabaseContext.MandrilWithSkillsIntermediateTable", b =>
                {
                    b.Property<int>("MandrilId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("PowerMS")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MandrilId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("MandrilWithSkills", null, t =>
                        {
                            t.HasCheckConstraint("power_limit_4", "PowerMS <= 4");
                        });
                });

            modelBuilder.Entity("MandrilAPI.Infrastructure.DatabaseContext.MandrilWithSkillsIntermediateTable", b =>
                {
                    b.HasOne("MandrilAPI.Domain.Models.Mandril", "Mandril")
                        .WithMany()
                        .HasForeignKey("MandrilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MandrilAPI.Domain.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandril");

                    b.Navigation("Skill");
                });
#pragma warning restore 612, 618
        }
    }
}
